"""Capability detection for VPN-Bench runtime cores.

The matrix is deliberately conservative: a protocol is marked supported only
when the current adapter can actually build its configuration.
"""

from __future__ import annotations

from dataclasses import dataclass
import os
import shutil


@dataclass(frozen=True)
class CoreCapability:
    core: str
    supported: bool
    reason: str


# These are the protocols currently generated by adapters/singbox.py.
LX_PROTOCOLS = {
    "vless",
    "vmess",
    "trojan",
    "ss",
    "shadowsocks",
    "hysteria2",
    "hy2",
    "tuic",
    "anytls",
    "ssh",
    "socks5",
    "socks",
    "naiveproxy",
}
LX_TRANSPORTS = {
    "tcp",
    "udp",
    "ws",
    "websocket",
    "grpc",
    "http",
    "httpupgrade",
    "quic",
    "xhttp",
}

# Extended currently shares the sing-box config generator with LX. It gets
# the same protocol set plus the extended XHTTP transport. Protocols such as
# SSH, MASQUE, Mieru and TrustTunnel are intentionally not advertised until
# they have a native builder in our adapter.
EXTENDED_PROTOCOLS = set(LX_PROTOCOLS)
EXTENDED_TRANSPORTS = set(LX_TRANSPORTS)

WIREGUARD_PROTOCOLS = {"wireguard", "amneziawg"}
WIREGUARD_TRANSPORTS = {"udp"}

XRAY_PROTOCOLS = {"vless"}
XRAY_TRANSPORTS = {"tcp", "raw", "ws", "websocket", "grpc", "xhttp", "httpupgrade"}


def detect_capabilities(protocol: str | None, transport: str | None) -> tuple[CoreCapability, ...]:
    protocol = (protocol or "").lower()
    transport = (transport or "tcp").lower()

    lx = protocol in LX_PROTOCOLS and transport in LX_TRANSPORTS
    extended = protocol in EXTENDED_PROTOCOLS and transport in EXTENDED_TRANSPORTS
    wireguard = protocol == "wireguard" and transport in WIREGUARD_TRANSPORTS
    amneziawg = protocol == "amneziawg" and transport in WIREGUARD_TRANSPORTS
    xray_binary = os.environ.get("VPN_BENCH_XRAY_BINARY", "xray")
    xray_available = shutil.which(xray_binary) is not None
    xray = xray_available and protocol in XRAY_PROTOCOLS and transport in XRAY_TRANSPORTS

    return (
        CoreCapability(
            "sing-box-lx",
            lx,
            "supported by the current LX adapter"
            if lx
            else "protocol/transport is outside the current LX adapter",
        ),
        CoreCapability(
            "sing-box-extended",
            extended,
            "supported by the current Extended adapter"
            if extended
            else "requires an adapter/config generator not implemented yet",
        ),
        CoreCapability(
            "wireguard-tools",
            wireguard,
            "supported by the isolated wg-quick adapter"
            if wireguard
            else "not used for AmneziaWG or unsupported protocol",
        ),
        CoreCapability(
            "sing-box-lx",
            amneziawg,
            "supported by the isolated AWG endpoint adapter"
            if amneziawg
            else "not used for this protocol",
        ),
        CoreCapability(
            "xray",
            xray,
            "supported by the Xray compatibility adapter"
            if xray
            else (
                "Xray binary is not installed"
                if not xray_available
                else "not supported by the current Xray adapter"
            ),
        ),
    )


def preferred_cores(protocol: str | None, transport: str | None) -> tuple[str, ...]:
    seen: set[str] = set()
    result: list[str] = []
    for item in detect_capabilities(protocol, transport):
        if item.supported and item.core not in seen:
            seen.add(item.core)
            result.append(item.core)
    return tuple(result)
