from fastapi.responses import HTMLResponse

HTML = """<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VPN-Bench</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#172033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}
.shell{display:flex;min-height:100vh}.side{width:225px;background:#172033;color:#dce4f2;padding:22px 14px;position:fixed;inset:0 auto 0 0}
.brand{font-weight:800;font-size:18px;padding:0 12px 28px}.brand b{color:#4b8cff}.nav button{display:block;width:100%;border:0;background:transparent;color:#b8c3d7;text-align:left;padding:11px 12px;border-radius:9px;margin:3px 0;cursor:pointer;font-size:14px}.nav button.active,.nav button:hover{background:#263653;color:white}.bottom{position:absolute;bottom:20px;left:14px;color:#8290a8;font-size:12px}
.main{margin-left:225px;width:calc(100% - 225px);padding:30px;max-width:1500px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.top h1{margin:0 0 5px;font-size:28px}.muted{color:#758198;font-size:13px}
.card{background:white;border:1px solid #e4e8f0;border-radius:14px;padding:18px;box-shadow:0 4px 18px rgba(22,32,51,.04)}.grid{display:grid;gap:16px}.stats{grid-template-columns:repeat(4,1fr)}
.stat strong{display:block;font-size:28px;margin-top:8px}.row{display:grid;grid-template-columns:1.5fr 1fr;gap:16px;margin-top:16px}
.progress{height:10px;background:#e9edf5;border-radius:10px;overflow:hidden}.bar{height:100%;background:#3478f6;border-radius:10px}
.btn{border:0;background:#246df3;color:white;padding:10px 16px;border-radius:9px;font-weight:650;cursor:pointer}.btn.secondary{background:#eef3fb;color:#315078}.btn.danger{background:#e5484d}
.input,select{width:100%;border:1px solid #d4dbe7;border-radius:9px;padding:10px 12px;background:white;font:inherit}.table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{text-align:left;padding:11px 8px;border-bottom:1px solid #edf0f5}.pill{display:inline-block;padding:4px 8px;border-radius:99px;background:#edf7ef;color:#238447;font-size:11px}.empty{padding:35px;text-align:center;color:#8490a4}
.cards{display:grid;grid-template-columns:1fr 1fr;gap:14px}.mode{border:2px solid #e2e7ef;border-radius:13px;padding:16px;cursor:pointer}.mode.selected{border-color:#3478f6;background:#f6f9ff}
.checktree{max-height:420px;overflow:auto;border:1px solid #e2e7ef;border-radius:10px;padding:10px}.providerline{font-weight:700;padding:9px 5px}.serverline{padding:6px 5px 6px 22px}.filter{display:flex;gap:8px;margin:7px 0}.filter input{flex:1}
@media(max-width:900px){.side{width:68px}.brand{font-size:0}.brand b{font-size:18px}.nav button{font-size:0;text-align:center}.main{margin-left:68px;width:calc(100% - 68px);padding:18px}.stats,.cards,.row{grid-template-columns:1fr}}
</style></head>
<body><div class="shell"><aside class="side"><div class="brand">◉ <b>VPN-Bench</b></div><nav class="nav">
<button data-page="dashboard" class="active">⌂ &nbsp; Дашборд</button><button data-page="providers">◉ &nbsp; Провайдеры</button><button data-page="servers">◌ &nbsp; Серверы</button><button data-page="tests">▶ &nbsp; Тесты</button><button data-page="analytics">▥ &nbsp; Аналитика</button><button data-page="logs">≡ &nbsp; Логи</button><button data-page="settings">⚙ &nbsp; Настройки</button>
</nav><div class="bottom">v0.2.0</div></aside><main class="main"><div id="app"></div></main></div>
<script>
var state={page:"dashboard",servers:[],providers:[],selected:{},mode:"equal_time",duration:600,filters:[""]};
var app=document.getElementById("app");
function esc(v){return String(v||"").replace(/[&<>"]/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]})}
function fmt(s){s=Math.max(0,Math.round(s||0));var h=Math.floor(s/3600);s%=3600;var m=Math.floor(s/60);var x=s%60;return (h?String(h).padStart(2,"0")+":":"")+String(m).padStart(2,"0")+":"+String(x).padStart(2,"0")}
async function api(p,o){var r=await fetch(p,Object.assign({headers:{"Content-Type":"application/json"}},o||{}));if(!r.ok){var e={};try{e=await r.json()}catch(_){ }throw new Error(e.detail||"Ошибка")};return r.json()}
async function boot(){var s=await api("/api/v1/setup/status");if(!s.configured){setupPage();return}try{await api("/api/v1/auth/me")}catch(_){loginPage();return}await refresh();render()}
function setupPage(){app.innerHTML='<div class="card" style="max-width:520px;margin:10vh auto"><h1>Добро пожаловать в VPN-Bench</h1><p class="muted">Создайте пароль администратора. Минимум 12 символов.</p><input id="p1" class="input" type="password" placeholder="Пароль"><br><br><input id="p2" class="input" type="password" placeholder="Повторите пароль"><br><br><button class="btn" onclick="setup()">Создать администратора</button></div>'}
async function setup(){var a=document.getElementById("p1").value,b=document.getElementById("p2").value;if(a!==b)return alert("Пароли не совпадают");try{await api("/api/v1/setup",{method:"POST",body:JSON.stringify({password:a})});await refresh();render()}catch(e){alert(e.message)}}
function loginPage(){app.innerHTML='<div class="card" style="max-width:420px;margin:10vh auto"><h1>VPN-Bench</h1><p class="muted">Вход администратора</p><input id="lp" class="input" type="password" placeholder="Пароль" onkeydown="if(event.key===\'Enter\')login()"><br><br><button class="btn" onclick="login()">Войти</button></div>'}
async function login(){try{await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({password:document.getElementById("lp").value})});await refresh();render()}catch(e){alert("Неверный пароль")}}
async function refresh(){state.providers=await api("/api/v1/providers");state.servers=await api("/api/v1/servers")}
function nav(){document.querySelectorAll(".nav button").forEach(function(b){b.onclick=function(){state.page=b.dataset.page;document.querySelectorAll(".nav button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");render()}})}
function head(t,s){return '<div class="top"><div><h1>'+t+'</h1><div class="muted">'+s+'</div></div></div>'}
async function render(){nav();if(state.page==="dashboard")return dashboard();if(state.page==="providers")return providers();if(state.page==="servers")return servers();if(state.page==="tests")return tests();if(state.page==="analytics")return placeholder("Аналитика","Графики и сравнение");if(state.page==="logs")return placeholder("Логи","Технические события и диагностика");return settings()}
async function dashboard(){var d=await api("/api/v1/dashboard"),t=d.test;app.innerHTML=head("Обзор","Краткая статистика по провайдерам и серверам")+'<div class="grid stats"><div class="card">Провайдеры<strong>'+d.providers+'</strong><span class="muted">подключено</span></div><div class="card">Серверы<strong>'+d.servers+'</strong><span class="muted">в базе</span></div><div class="card">Измерения<strong>'+d.results+'</strong><span class="muted">сохранено</span></div><div class="card">Статус<strong>'+((t.status==="running")?"Тестируется":"Готов")+'</strong><span class="muted">'+t.status+'</span></div></div><div class="card" style="margin-top:16px"><h3>Текущий тест</h3>'+summary(t)+'</div>';if(t.status==="running")setTimeout(dashboard,1000)}
function summary(t){if(!t||t.status==="idle")return '<div class="empty">Тестирование не запущено</div>';return '<div style="display:flex;justify-content:space-between"><b>'+esc(t.current_server_name||"Завершение")+'</b><span>'+t.completed_servers+'/'+t.total_servers+'</span></div><div class="progress" style="margin:12px 0"><div class="bar" style="width:'+t.progress+'%"></div></div><div class="muted">Прогресс '+t.progress+'% · прошло '+fmt(t.elapsed_seconds)+' · осталось '+(t.remaining_seconds==null?"рассчитывается":fmt(t.remaining_seconds))+' · '+esc(t.message)+'</div>'}
function providers(){var rows=state.providers.map(function(p){var n=state.servers.filter(function(s){return s.provider_id===p.id}).length;return '<tr><td><b>'+esc(p.display_name||p.name)+'</b><br><span class="muted">'+esc(p.name)+'</span></td><td>'+n+'</td><td><span class="pill">Активен</span></td><td>'+esc(p.last_updated_at||"—")+'</td></tr>'}).join("");app.innerHTML=head("Провайдеры","Подписки, метаданные и состояние обновления")+'<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><b>Подключенные провайдеры</b><button class="btn" onclick="addProvider()">Добавить провайдера</button></div><table class="table"><thead><tr><th>Название</th><th>Серверов</th><th>Статус</th><th>Обновлено</th></tr></thead><tbody>'+(rows||'<tr><td colspan="4" class="empty">Провайдеров пока нет</td></tr>')+'</tbody></table></div>'}
async function addProvider(){var n=prompt("Название (оставьте пустым, чтобы определить автоматически):");var u=prompt("URL подписки:");if(!u)return;try{await api("/api/v1/providers",{method:"POST",body:JSON.stringify({name:n||"Определяется",display_name:n||null,subscription_url:u})});await refresh();render()}catch(e){alert(e.message)}}
function servers(){var rows=state.servers.map(function(s){return '<tr><td>'+esc(s.provider)+'</td><td><b>'+esc(s.name)+'</b></td><td>'+esc(s.protocol||"—")+'</td><td>'+esc(s.transport||"—")+'</td><td>'+esc(s.security||"—")+'</td><td>—</td><td>—</td></tr>'}).join("");app.innerHTML=head("Серверы","Все серверы из подключенных провайдеров")+'<div class="card"><table class="table"><thead><tr><th>Провайдер</th><th>Сервер</th><th>Протокол</th><th title="Способ передачи данных: XHTTP, WebSocket, gRPC и т.д.">Транспорт ⓘ</th><th title="Криптографическая защита соединения: TLS, Reality и т.д.">Защита ⓘ</th><th title="Время прохождения запроса до сервера и обратно.">Ping ⓘ</th><th title="Доля успешных проверок сервера за выбранный период.">Доступность ⓘ</th></tr></thead><tbody>'+(rows||'<tr><td colspan="7" class="empty">Серверов пока нет</td></tr>')+'</tbody></table></div>'}
function tests(){var count=Object.keys(state.selected).length;var tree=state.providers.map(function(p){var ss=state.servers.filter(function(s){return s.provider_id===p.id||s.provider===p.name});var ch='<div class="providerline"><b>'+esc(p.display_name||p.name)+'</b></div>';ss.forEach(function(s){ch+='<div class="serverline"><label><input type="checkbox" '+(state.selected[s.id]?"checked":"")+' onchange="toggle(\''+s.id+'\',this.checked)"> '+esc(s.name)+'</label></div>'});return ch}).join("");app.innerHTML=head("Тестирование","Выберите серверы, продолжительность и режим")+'<div class="row"><div class="card"><h3>Серверы</h3>'+filterHtml()+'<div class="checktree">'+(tree||'<div class="empty">Добавьте провайдеров</div>')+'</div></div><div><div class="card"><h3>Продолжительность</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="dur" title="Общая продолжительность всей тестовой кампании." class="input" type="number" min="1" value="'+Math.max(1,Math.round(state.duration/60))+'"><select id="unit" class="input"><option value="60">минут</option><option value="3600">часов</option><option value="86400">дней</option><option value="604800">недель</option><option value="2592000">месяцев</option></select></div><div class="cards" style="margin-top:14px"><div class="mode '+(state.mode==="equal_time"?"selected":"")+'" onclick="state.mode=\'equal_time\';render()"><h3>Равное время</h3><div class="muted">Общее время делится поровну между выбранными серверами.</div><p><b>'+(count?fmt(state.duration/count):"—")+'</b> на сервер</p></div><div class="mode '+(state.mode==="sequential"?"selected":"")+'" onclick="state.mode=\'sequential\';render()"><h3>Последовательно</h3><div class="muted">Сервер тестируется до завершения набора проверок, затем запускается следующий.</div></div></div><p class="muted">Выбрано: '+count+' · общее время: '+fmt(state.duration)+'</p><button class="btn" onclick="startTest()">Запустить тест</button></div><div class="card" style="margin-top:16px"><h3>Текущий статус</h3><div id="status">Загрузка…</div></div></div></div>';document.getElementById("dur").onchange=function(){state.duration=Number(this.value)*Number(document.getElementById("unit").value);render()};document.getElementById("unit").onchange=function(){state.duration=Number(document.getElementById("dur").value)*Number(this.value);render()};loadStatus()}
function filterHtml(){return '<div class="filter"><input class="input" placeholder="Исключить по регулярному выражению" value="'+esc(state.filters[0])+'"><button class="btn secondary" onclick="addFilter()">+</button></div>'}
function addFilter(){state.filters.push("");render()}
function toggle(id,on){if(on)state.selected[id]=true;else delete state.selected[id]}
async function startTest(){var ids=Object.keys(state.selected);if(!ids.length)return alert("Выберите хотя бы один сервер");try{await api("/api/v1/tests",{method:"POST",body:JSON.stringify({server_ids:ids,duration_seconds:state.duration,scheduling_mode:state.mode})});loadStatus()}catch(e){alert(e.message)}}
async function loadStatus(){try{var t=await api("/api/v1/tests/latest"),el=document.getElementById("status");if(!el)return;el.innerHTML=summary(t)+(t.status==="running"||t.status==="stopping"?'<br><button class="btn danger" onclick="stopTest(\''+t.run_id+'\')">Остановить</button>':"");if(t.status==="running")setTimeout(loadStatus,1000)}catch(_){ }}
async function stopTest(id){await api("/api/v1/tests/"+id+"/stop",{method:"POST"});loadStatus()}
function placeholder(t,s){app.innerHTML=head(t,s)+'<div class="card"><div class="empty">Этот раздел уже заложен в структуру приложения. Реальные данные появятся после подключения движка измерений.</div></div>'}
function settings(){app.innerHTML=head("Настройки","Хранение, сеть, безопасность и обновления")+'<div class="grid" style="grid-template-columns:1fr 1fr"><div class="card"><h3>Безопасность</h3><p class="muted">Смена пароля администратора.</p><button class="btn secondary">Изменить пароль</button></div><div class="card"><h3>Система</h3><p>Версия <b>0.2.0</b></p><p class="muted">Проверка обновлений и обновление приложения.</p><button class="btn secondary">Проверить обновления</button></div><div class="card"><h3>Хранение</h3><p class="muted">Срок хранения результатов и очистка старых измерений.</p></div><div class="card"><h3>Сеть</h3><p class="muted">DNS, IPv4/IPv6 и тестовые endpoints.</p></div></div>'}
boot();
</script></body></html>"""

def page() -> HTMLResponse:
    return HTMLResponse(HTML)
